apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    # repoURL: https://prometheus-community.github.io/helm-charts
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: "2.11.0"
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
